import type { Metadata } from "next";
import localFont from "next/font/local";
import HeaderNav from "@/components/header";

import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["500", "400", "600", "700", "300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased max-w-[360px] pt-[72px]`}
      >
        <HeaderNav />
        {children}
      </body>
    </html>
  );
}
